### ISSUE TITLE
Add gitlab_pages_enable to gitlab.rb.j2

### ISSUE THREAD

**Issue by matteo-brancazi** [cristianocasella/ansible-role-gitlab#4]
# Issue Description

The configuration of the file [gitlab.rb.j2](https://github.com/cristianocasella/ansible-role-gitlab/blob/main/templates/gitlab.rb.j2) is missing an important parameter to enable GitLab Pages correctly.

---

## Solution

Adding the following string should fix this this issue: `gitlab_pages['enable'] = "{{ gitlab_pages_enable }}"`

**Comment by matteo-brancazi** [comment]
The configuration can be done also by adding the following script instead of editing the [gitlab.rb.j2](https://github.com/cristianocasella/ansible-role-gitlab/blob/main/templates/gitlab.rb.j2)

```yaml
gitlab_extra_settings:
  - gitlab_pages:
      - key: "dependency_proxy_enabled"
        value: "false"
```
