### ISSUE TITLE
Add the new feature AI Gateway

### ISSUE THREAD

**Issue by RiccardoTOTI** [cristianocasella/ansible-role-gitlab#5]
# Summary
With the new GitLab release [v17.5.1-ee](https://gitlab.com/gitlab-org/gitlab/-/tags/v17.5.1-ee), it is now possible to configure self-hosted AI models to provide code suggestions, GitLab Duo, and other features. This functionality requires updates to the gitlab.rb configuration file.

## Problem
Currently, the role does not support adding the required gitlab_rails['env'] configuration for self-hosted model connections. According to the [GitLab documentation](https://docs.gitlab.com/ee/administration/self_hosted_models/install_infrastructure.html#configure-your-gitlab-instance), the following configuration is necessary in gitlab.rb:

```bash
gitlab_rails['env'] = {
  'GITLAB_LICENSE_MODE' => 'production',
  'CUSTOMER_PORTAL_URL' => 'https://customers.gitlab.com',
  'AI_GATEWAY_URL' => '<path_to_your_ai_gateway>:<port>'
}
```

## Proposed Solution
To implement this configuration, update the gitlab_extra_settings Jinja template to support the gitlab_rails['env'] dictionary format, allowing dynamic configuration of these settings. The following Jinja template update illustrates the proposed logic:

```jinja
{% if gitlab_extra_settings is defined %}
# Extra configuration
{% for extra in gitlab_extra_settings %}
{% for setting in extra %}
{% for kv in extra[setting] %}
{% if kv.key == 'env' and kv.value is mapping %}
{{ setting }}['{{ kv.key }}'] = {
{% for env_key, env_value in kv.value.items() %}
  '{{ env_key }}' => '{{ env_value }}',
{% endfor %}
}
{% elif (kv.type is defined and kv.type == 'plain') or (kv.value is not string) %}
{{ setting }}['{{ kv.key }}'] = {{ kv.value }}
{% else %}
{{ setting }}['{{ kv.key }}'] = '{{ kv.value }}'
{% endif %}
{% endfor %}
{% endfor %}
{% endfor %}
{% endif %}
```
## Example Configuration

The main main.yml with variable definitions might look like this:

```yaml
gitlab_extra_settings:
  - gitlab_rails:
      - key: "dependency_proxy_enabled"
        value: "false"
      - key: "env"
        value:
          GITLAB_LICENSE_MODE: "production"
          CUSTOMER_PORTAL_URL: "https://customers.gitlab.com"
          AI_GATEWAY_URL: "<path_to_your_ai_gateway>:<port>"
  - gitlab_pages:
      - key: "enable"
        value: "true"
```

## Additional Context
Implementing this change will enable users to leverage self-hosted models for various GitLab features by configuring the gitlab.rb file dynamically through Ansible.
